import 'dart:typed_data';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

/// Generates and shares PDF reports from markdown content.
class PdfService {
  Future<void> generatePdfFromMarkdown(
    String markdown,
    String fileName,
    String patientId,
    String period,
  ) async {
    final pdf = pw.Document();
    final content = _parseMarkdown(markdown);

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        build: (_) => [
          _buildHeader(patientId, period),
          pw.SizedBox(height: 20),
          ...content,
          pw.SizedBox(height: 30),
          _buildFooter(),
        ],
      ),
    );

    await Printing.sharePdf(bytes: await pdf.save(), filename: fileName);
  }

  Future<void> shareReport(String markdown, String patientId, String period) async {
    final fileName = 'neurolens_report_${patientId}_${DateTime.now().millisecondsSinceEpoch}.pdf';
    await generatePdfFromMarkdown(markdown, fileName, patientId, period);
  }

  pw.Widget _buildHeader(String patientId, String period) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text(
                  'NeuroLens',
                  style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold, color: PdfColors.blue800),
                ),
                pw.Text(
                  'Cognitive Health Report',
                  style: const pw.TextStyle(fontSize: 16, color: PdfColors.grey700),
                ),
              ],
            ),
            pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.end,
              children: [
                pw.Text('Patient: $patientId', style: pw.TextStyle(fontSize: 12, fontWeight: pw.FontWeight.bold)),
                pw.Text('Period: $period', style: const pw.TextStyle(fontSize: 12, color: PdfColors.grey700)),
                pw.Text(
                  'Generated: ${DateTime.now().toString().substring(0, 19)}',
                  style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey600),
                ),
              ],
            ),
          ],
        ),
        pw.SizedBox(height: 10),
        pw.Container(height: 1, color: PdfColors.blue800),
      ],
    );
  }

  pw.Widget _buildFooter() {
    return pw.Column(
      children: [
        pw.Container(height: 1, color: PdfColors.grey300),
        pw.SizedBox(height: 10),
        pw.Text(
          'This report is generated by NeuroLens AI and should be reviewed with healthcare professionals.',
          style: pw.TextStyle(fontSize: 9, color: PdfColors.grey600, fontStyle: pw.FontStyle.italic),
          textAlign: pw.TextAlign.center,
        ),
        pw.SizedBox(height: 5),
        pw.Text(
          'For questions or concerns, please contact your healthcare provider.',
          style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey600),
          textAlign: pw.TextAlign.center,
        ),
      ],
    );
  }

  List<pw.Widget> _parseMarkdown(String markdown) {
    final lines = markdown.split('\n');
    final widgets = <pw.Widget>[];

    for (final line in lines) {
      if (line.trim().isEmpty) {
        widgets.add(pw.SizedBox(height: 5));
        continue;
      }

      if (line.startsWith('# ')) {
        widgets.add(pw.SizedBox(height: 15));
        widgets.add(pw.Text(
          line.substring(2),
          style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold, color: PdfColors.blue800),
        ));
        widgets.add(pw.SizedBox(height: 10));
      } else if (line.startsWith('## ')) {
        widgets.add(pw.SizedBox(height: 12));
        widgets.add(pw.Text(
          line.substring(3),
          style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold, color: PdfColors.blue700),
        ));
        widgets.add(pw.SizedBox(height: 8));
      } else if (line.startsWith('### ')) {
        widgets.add(pw.SizedBox(height: 10));
        widgets.add(pw.Text(
          line.substring(4),
          style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold, color: PdfColors.grey800),
        ));
        widgets.add(pw.SizedBox(height: 6));
      } else if (line.startsWith('- ') || line.startsWith('* ')) {
        widgets.add(pw.Padding(
          padding: const pw.EdgeInsets.only(left: 15, bottom: 3),
          child: pw.Row(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text('• ', style: const pw.TextStyle(fontSize: 12)),
              pw.Expanded(child: pw.Text(line.substring(2), style: const pw.TextStyle(fontSize: 12, height: 1.4))),
            ],
          ),
        ));
      } else {
        widgets.add(pw.Text(line, style: const pw.TextStyle(fontSize: 12, height: 1.4, color: PdfColors.grey800)));
        widgets.add(pw.SizedBox(height: 3));
      }
    }

    return widgets;
  }
}